services:
  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000

  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend
    environment:
      - MONGO_URL=mongodb://root:password@mongo:27017/database
      - BACKEND_PORT=3001
    ports:
      - 3001:3001
    depends_on: 
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: database
    volumes:
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js