version: '3.8'
services:
  frontend:
    image: phonebook-front
    container_name: phonebook-front
    build:
      context: ./frontend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    ports: 
      - 3000:3000 # This will map the port 3000 of the container to the port 3000 of the host machine
    environment:
      - NODE_ENV=production
    
  backend:
    image: phonebook-back
    container_name: phonebook-back
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://username:password@mongo:27017/database
      - BACKEND_PORT=3001
      - NODE_ENV=production
    ports: 
      - 3001:3001
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo/data:/data/db
